### ISSUE TITLE
question: pattern for a middleware that resets the chain

### ISSUE THREAD

**Issue by jokeyrhyme** [alessioalex/generic-middleware#11]
I have a use case where I want a middleware to be able to reset the chain. More specifically, I want a "loginNeeded" middleware to detect when authentication hasn't been performed, and redirect to a login route.

I have a `routeRequest()` function that calls `Middleware#init()`, which starts my middleware stack.

I've outlined a few ideas below. Any of them will work, I'm just curious about what others think about this problem.
## approach A:

just call `routeRequest()` instead of `next()`
- means my middleware function needs access to `routeRequest()` (seems like a weird pattern)
## approach B:

call `Middleware#init()` instead of `next()`
- means my middleware function needs access to the middleware stack (seems less weird, but still weird)
## approach C:

new `ResetMiddlewareError`, pass it to `next(err)`, and have the registered error handler call either `routeRequest()` or `Middleware#init()`
- keeps individual middleware functions simple in terms of what they need to access
- seems to be an abuse of the error handler, which is now more complex as a result

**Comment by alessioalex** [comment]
Hey!

Maybe I'm missing something / misread but I'm thinking of the following: place your authentication function before the others in the stack that need it and actually redirect to the login page if it's the case (as you would do with Express by using `res.redirect()` - thus automatically creating a new request which "resets" the middleware stack).

If I'm mistaken let me know and maybe also provide a small snippet of code as well.

**Comment by jokeyrhyme** [comment]
Well, I'm not actually using Express. `res.redirect()` is effectively the same as passing my `routeRequest()` to all of my middleware, which is probably cleaner than providing access to it via variable scope or module import. So this is pretty much my "A" approach, but with a specific implementation detail.

There's not really much difference between the A and B approaches really. The custom Error thing with C smelled funny, so I don't think I'll do that. :)

**Comment by alessioalex** [comment]
Yeah if `routeRequest()` is your `res.redirect()` equivalent, then approach A is how I would do it.
